all: euler.dat rk4.dat leapfrog.dat

%.dat: DanielaBarrios_Ejercicio26.x
	./DanielaBarrios_Ejercicio26.x

DanielaBarrios_Ejercicio26.x: DanielaBarrios_Ejercicio26.cpp
	c++ DanielaBarrios_Ejercicio26.cpp -o DanielaBarrios_Ejercicio26.x

clean:
	rm -rf *.x *.dat
